### ISSUE TITLE
Support node 0.10

### ISSUE THREAD

**Issue by balupton** [bevry/assert-helpers#3]

**Comment by RobLoach** [comment]
Why? Node 0.10 is so old. :-1:

**Comment by balupton** [comment]
Meteor still uses it apparently. Spent the day re-adding node 0.10 compat to other modules as some meteor folk use them, especially bevry/cson

**Comment by balupton** [comment]
With the new https://github.com/bevry/assert-helpers#editions section that mentions the babel polyfill, this can be closed.
